### ISSUE TITLE
You must be logged in before call the method Picasa::checkPermission

### ISSUE THREAD

**Issue by phuclh** [ptcong/php-image-uploader#5]
When I select 2 images (~2MB), it's OK. But when I select about 20 images (~15MB) I got a message:
`You must be logged in before call the method Picasa::checkPermission`

Thank you !!!

**Comment by ptcong** [comment]
I've test upload an image size 23.4Mb, it still works fine.
May be your session has expired.

**Comment by phuclh** [comment]
I think so. How can I increase session time. Sorry I upload ~45MB not 15MB. I'm confused.

**Comment by ptcong** [comment]
I think you are wrapped $uploader->login() in a if block checked by your flag (is logged in).
In nearly time, it still works, but after Picasa session expires but your flag still not expires,so when you call upload(), no session values sent.
Should always call the method before call upload to ensure that session comes with uploading.
Don't need to increase session time and don't need thinking how to optimize (only call login method if your flag is not set) because it’s already have.

**Comment by phuclh** [comment]
So how can I determine Picasa's session has expired ? This is my code:
https://gist.github.com/phuclh/a977217339fd301f8a73

**Comment by ptcong** [comment]
I don't remember how long auth token will be expires (you may check in picasa API document). I set it to 5 minutes to sure that token always refresh each 5 minutes.

`$uploader = $this->hostRepository->loginPicasa($host);`

Why don't you call ->login() instead of loginPicasa ? 
Because if you use other plugin, you can't call loginPicasa. 
If possible, you should use this

`$uploader = $this->hostRepository->loginPicasa($host);
$tranferedImageLink = $uploader->upload($link);`

**Comment by phuclh** [comment]
`loginPicasa` is the shortcut to `login` funcion.

public function loginPicasa($host)
    {
        $uploader = ChipVN_ImageUploader_Manager::make('Picasa');
        $uploader->login($host->identity, $host->password);

        return $uploader;
    }

I did a test. I upload 45 images (~45MB) and open the album page in Picasa. Until my session has expired, have 40 images was uploaded successfully and 5 was failed. I want to upload all of them in only a request but I lost session at 41th image.

**Comment by ptcong** [comment]
You can edit expires in Picasa plugin or do like i said above, make each uploader in each process. 
Login action only execute if session is expires.

**Comment by phuclh** [comment]
OK thank you very much :D
