### ISSUE TITLE
Video uploading to picasa

### ISSUE THREAD

**Issue by HaiDesu** [ptcong/php-image-uploader#6]
Are there any plans to support video uploading to Picasa?

**Comment by ptcong** [comment]
Already have in my laptop (can bypass picasa upload limited 100Mb), but need to use OAuth (hard to login silent) so i don't want to use it instead of google_client_login (it is old but support login silent).

And the project mainly helps to remote upload image - not video. 
If you want to upload video to picasa, you may try with Zend library
